export const FC_CATS = [
  { id: 'persons', icon: '👤', name: 'Persons & Who Said What' },
  { id: 'definitions', icon: '📚', name: 'Definitions & Full Forms' },
  { id: 'theories', icon: '🔬', name: 'Theories & Concepts' },
  { id: 'bloom', icon: '🌸', name: "Bloom's Taxonomy" },
  { id: 'assessment', icon: '📊', name: 'Assessment Types' },
  { id: 'brain', icon: '🧠', name: 'Brain & Intelligence' },
  { id: 'communication', icon: '💬', name: 'Communication' },
];

export const FC_CARDS: Record<string, { q: string; a: string }[]> = {
  persons: [
    { q: "Who introduced and popularised the concept of Andragogy?", a: "<b>Malcolm Knowles</b> popularised Andragogy in the USA. <b>Alexander Kapp</b> first coined the term in 1833." },
    { q: "Who created Bloom's Taxonomy and when?", a: "<b>Benjamin S. Bloom</b> created it in <b>1956</b>. Revised by <b>Lorin Anderson</b> in 2001 — renamed 'A Taxonomy for Teaching, Learning and Assessment.'" },
    { q: "Who revised Bloom's Taxonomy and what was the key change?", a: "<b>Lorin Anderson</b> (Bloom's student) revised it in 2001. Changed nouns to <b>action verbs</b>. Moved Synthesis to the top as <b>CREATE</b>." },
    { q: "Who developed the VARK learning style model and when?", a: "<b>Neil Fleming</b> in <b>1987</b> in New Zealand. VARK = Visual, Auditory, Reading/Writing, Kinesthetic." },
    { q: "Who defined self-concept as 'totality of attitudes, judgement and values'?", a: "<b>H.J. Eysenck</b>. Full definition: 'The totality of attitudes, judgement and values of an individual relating to his behavior, abilities and qualities.'" },
    { q: "Who created the Inkblot (Rorschach) Test?", a: "<b>Hermann Rorschach</b>. Key work: Psychodiagnostik (1921). It is a projective personality assessment." },
    { q: "Who created the TAT (Thematic Apperception Test)?", a: "<b>Morgan and Murray</b> — NOT Rorschach. A common PYQ trap." },
    { q: "Who created the 16PF (Personality Factor Test)?", a: "<b>Raymond Cattell</b>." },
    { q: "Who said 'Training has been a successful method of reducing accidents'?", a: "<b>Walter</b> — NOT Thorndike. This is a direct PYQ attribution question." },
    { q: "Who defined communication as 'the process of meaningful interaction among human beings'?", a: "<b>Meferland</b>. This is his definition — frequently tested in PYQs." },
    { q: "Who said 'Educational psychology describes learning from birth to old age'?", a: "<b>L.D. Crow and Alice Crow</b> — NOT Skinner. Common PYQ trap." },
    { q: "Who are the two key thinkers of Critical Pedagogy?", a: "<b>Paulo Freire</b> and <b>Henry Giroux</b>. Loughran = reflective teaching (NOT critical pedagogy)." },
    { q: "What is Paulo Freire famous for?", a: "<b>Critical Pedagogy</b>. Criticised the 'Banking Model' of education. Key work: Pedagogy of the Oppressed (1968)." },
    { q: "What is the Banking Model of Education (Freire)?", a: "Traditional education where the teacher 'deposits' knowledge into passive students like a bank. Freire <b>CRITICISED</b> this model." },
    { q: "Who proposed the Theory of Multiple Intelligences?", a: "<b>Howard Gardner</b> (1983). Multiple intelligences include Linguistic, Logical-Mathematical, Spatial, Musical, Bodily-Kinesthetic, Interpersonal, Intrapersonal, Naturalist." },
    { q: "Which two intelligences from Gardner are tested in NTET PYQs?", a: "<b>Interpersonal</b> and <b>Naturalist</b>. Conversational proficiency, Innovative, Pragmatic are NOT Gardner's intelligences." },
    { q: "Who is associated with Schema Theory?", a: "<b>BOTH Frederic Bartlett AND Jean Piaget</b>. Vygotsky and Bronfenbrenner are common distractors." },
    { q: "Who proposed the Hierarchy of Needs?", a: "<b>Abraham Maslow</b> (1943) in 'A Theory of Human Motivation'." },
    { q: "Who invented Operant Conditioning?", a: "<b>B.F. Skinner</b>. Voluntary behaviour shaped by consequences (reinforcement/punishment)." },
    { q: "Who invented Classical Conditioning?", a: "<b>Ivan Pavlov</b>. Famous for dogs salivating at a bell (Nobel Prize 1904)." },
    { q: "Who invented Trial and Error Learning / Connectionism?", a: "<b>Edward L. Thorndike</b>. Theory name = CONNECTIONISM." },
    { q: "Who invented the Teaching Machine?", a: "<b>B.F. Skinner</b> — forerunner of modern e-learning and Computer-Assisted Instruction (CAI)." },
    { q: "Who developed the Ecological Systems Theory?", a: "<b>Urie Bronfenbrenner</b>. Theory is ECOLOGICAL (not structural)." },
    { q: "Who said 'problems should be those solvable by students using their intellect'?", a: "<b>Hunt</b> — NOT Tassinari. PYQ directly tests this attribution." },
    { q: "Who described responsibilities of adult trainers as Facilitator and Harmonizer?", a: "<b>Liegans Paul</b>. (Knowles = Andragogy concept; Lieb = motivation & reinforcement; Hall D.M. = guidelines)" },
    { q: "Who described critical elements of adult learning including motivation and reinforcement?", a: "<b>Stephen Lieb</b>." },
    { q: "Who described guidelines for adult trainers?", a: "<b>Hall D.M.</b>" },
    { q: "Who coined the term Andragogy first in history?", a: "<b>Alexander Kapp</b> in <b>1833</b>. Knowles popularised it much later." },
    { q: "Who developed Connectivism learning theory?", a: "<b>George Siemens</b> (2004) — a learning theory for the digital age." },
  ],
  definitions: [
    { q: "What does UDL stand for?", a: "<b>Universal Design for Learning</b>. NOT 'Unified' — this wrong spelling appears as a PYQ MCQ option. Developed by CAST." },
    { q: "What does CBCS stand for?", a: "<b>Choice Based Credit System</b>. NOT Content Based Credit System." },
    { q: "What does OSCE stand for?", a: "<b>Objective Structured Clinical Examination</b> — multiple timed stations testing specific clinical skills with standardised patients." },
    { q: "What does MEQ stand for?", a: "<b>Modified Essay Questions</b> — open-ended, case-based questions." },
    { q: "What does SJT stand for?", a: "<b>Situational Judgement Test</b> — multiple sections/questions based on ONE case scenario." },
    { q: "What does VARK stand for?", a: "<b>V</b>isual, <b>A</b>uditory, <b>R</b>eading/Writing, <b>K</b>inesthetic — Neil Fleming's learning style model." },
    { q: "What does ZPD stand for?", a: "<b>Zone of Proximal Development</b> — Vygotsky's concept. The gap between what a learner can do alone vs. with guidance." },
    { q: "What does CAI stand for?", a: "<b>Computer Assisted Instruction</b> — individualised learning using computers. Invented by Skinner (Teaching Machine concept)." },
    { q: "What does SWAYAM stand for?", a: "<b>Study Webs of Active Learning for Young Aspiring Minds</b>. India's national MOOC platform launched in 2017." },
    { q: "What does ICT stand for?", a: "<b>Information and Communication Technology</b> — includes both hardware AND software." },
    { q: "What does CLO stand for?", a: "<b>Course Learning Objectives</b> — detailed objectives for individual subjects/courses." },
    { q: "What does PLO stand for?", a: "<b>Program Learning Objectives</b>. Above CLOs in the hierarchy. GA = Graduate Attributes (even higher)." },
    { q: "What is the IQ formula?", a: "IQ = (<b>Mental Age ÷ Chronological Age</b>) × 100. Mental Age on top, Chronological Age on bottom." },
    { q: "What does ICMA stand for?", a: "<b>Interactive Computer Marked Assessment</b>." },
    { q: "What does LMS stand for?", a: "<b>Learning Management System</b>. Example: Moodle. NOT a video conferencing tool." },
    { q: "What does AR stand for in education?", a: "<b>Augmented Reality</b> — overlays digital information on a real-world environment. Different from VR (which replaces reality)." },
    { q: "What does MOOCs stand for?", a: "<b>Massive Open Online Courses</b>. SWAYAM is India's MOOC platform." },
    { q: "What does CBCS assessment include?", a: "CBCS assessment is INCLUSIVE: <b>formative + summative + project + field-based</b> practices — all types together, not just one." },
  ],
  theories: [
    { q: "What is the correct direction in Vygotsky's theory?", a: "<b>Interpsychological FIRST</b> (social, between people) → then <b>Intrapsychological</b> (internal, within the mind). NEVER reversed." },
    { q: "What is Scaffolding in Vygotsky's theory?", a: "<b>Temporary, adjustable support</b> provided within the ZPD. Gradually <b>removed</b> as the learner becomes competent. Types: hints, prompts, worked examples." },
    { q: "What is private speech according to Vygotsky?", a: "A <b>thinking tool</b> — children talking to themselves helps them solve problems. It is <b>NOT egocentric behaviour</b>." },
    { q: "What is assimilation in Piaget's theory?", a: "Fitting <b>new information into an existing schema</b> without changing the schema. Like calling all animals 'dog'." },
    { q: "What is accommodation in Piaget's theory?", a: "<b>Changing or creating a schema</b> to fit new information that doesn't fit. Learning that cats ≠ dogs." },
    { q: "In what pattern does a child move through Piaget's stages?", a: "<b>Established (fixed) pattern</b> — no stage can be skipped. The order is universal across all children." },
    { q: "What is the Chronosystem in Bronfenbrenner's theory?", a: "The <b>TIME dimension</b> — life transitions and historical events. Example: growing up before mobile phones (PYQ 2025)." },
    { q: "Is Bronfenbrenner's theory structural or ecological?", a: "<b>ECOLOGICAL</b> (Bioecological Model). 'Structural theory of learning' is a direct PYQ wrong option." },
    { q: "What is Connectionism (Thorndike)?", a: "Learning through forming <b>Stimulus-Response bonds</b>. Also called Trial and Error Learning. NOT the same as Classical or Operant Conditioning." },
    { q: "What is the difference between Operant and Classical Conditioning?", a: "<b>Classical (Pavlov)</b> = learning by association between stimuli (involuntary). <b>Operant (Skinner)</b> = voluntary behaviour shaped by consequences." },
    { q: "What is Mastery Learning (Bloom)?", a: "Almost <b>all students can learn to a high level</b> if given adequate time and appropriate instruction. Challenges the 'only some can succeed' notion." },
    { q: "What is the difference between Integration and Inclusion?", a: "<b>Integration</b> = student adapts to the institution. <b>Inclusion</b> = institution adapts to the student. Inclusion is more advanced." },
    { q: "What is Andragogy?", a: "Science and art of helping <b>adults learn</b>. Learner-centred, problem-centred, internally motivated. Coined by Kapp (1833), popularised by Knowles." },
    { q: "What does Pedagogy mean literally (Greek origin)?", a: "From Greek 'paidagogos' = to <b>LEAD the child</b>. Not educate, not mentor, not recognise — LEAD is the only correct answer." },
    { q: "What is Constructivism?", a: "Learners <b>actively BUILD</b> their own understanding — not passive receivers. Associated with Piaget (individual) and Vygotsky (social). Underpins inquiry-based and problem-based learning." },
    { q: "What is Connectivism (Siemens)?", a: "Learning theory for the <b>digital age</b>. Learning = making connections in a network (people, websites, databases). Associated with MOOCs and Social Networking." },
  ],
  bloom: [
    { q: "What are the 6 levels of Bloom's Cognitive Domain in order (lowest to highest)?", a: "<b>Remember → Understand → Apply → Analyse → Evaluate → Create</b>. Mnemonic: RUAAEC." },
    { q: "What is the highest level in Bloom's revised taxonomy?", a: "<b>Create</b> (was 'Synthesis' in the original 1956 taxonomy — renamed by Lorin Anderson in 2001)." },
    { q: "'Recognise linear equations' is which Bloom's level?", a: "<b>Remembering</b> — Level 1. It is recall/recognition of previously learned facts." },
    { q: "'Give examples of linear equations' is which Bloom's level?", a: "<b>Understanding</b> — Level 2. Giving examples shows comprehension beyond mere recall." },
    { q: "'Represent linear equation graphically' is which Bloom's level?", a: "<b>Applying</b> — Level 3. Using the concept (graphical representation) in a practical, concrete way." },
    { q: "What are the 5 levels of the Affective Domain in order?", a: "<b>Receiving → Responding → Valuing → Organisation → Characterization</b>. Mnemonic: RRVOC." },
    { q: "What are the 5 levels of Dave's Psychomotor Domain (1970)?", a: "<b>Imitation → Manipulation → Precision → Articulation → Naturalization</b>. Mnemonic: IMPAN." },
    { q: "What does 'Receiving' mean in the Affective Domain?", a: "<b>Passive attention</b>, awareness, willingness to hear — the LOWEST level of the affective domain." },
    { q: "What does 'Characterization' mean in the Affective Domain?", a: "Values completely <b>internalised</b> — they define the person's entire character. The <b>HIGHEST</b> level of the affective domain." },
    { q: "Who revised Bloom's Taxonomy and what is the revised version called?", a: "<b>Lorin Anderson</b> (2001). Renamed to: <b>'A Taxonomy for Teaching, Learning and Assessment'</b>." },
  ],
  assessment: [
    { q: "What is formative assessment?", a: "Assessment <b>DURING instruction</b>. Provides feedback. <b>Accelerates learning</b>. Examples: class tests, quizzes, assignments, teacher observation." },
    { q: "What is summative assessment?", a: "Assessment at the <b>END of instruction</b>. Certifies and grades. <b>Measures final learning</b>. Examples: final exams, term-end exams, board exams." },
    { q: "What is diagnostic assessment?", a: "Identifies <b>WHY a student is struggling</b>. Done before or during teaching to find persistent learning difficulties." },
    { q: "What is periodic assessment?", a: "Serves <b>BOTH formative AND diagnostic</b> purposes — NOT summative. This exact combo is tested in PYQ 2025." },
    { q: "What is placement assessment?", a: "Determines where to <b>place a student BEFORE</b> instruction begins. Based on prior knowledge." },
    { q: "What is norm-referenced assessment?", a: "Performance compared <b>relative to the group</b> — ranks students against each other. Who is above/below average." },
    { q: "What is criterion-referenced assessment?", a: "Performance compared against a <b>set standard</b> or cut-off (pass/fail). Not compared to peers." },
    { q: "What is ipsative (self-referenced) assessment?", a: "Current performance compared with the <b>student's OWN earlier performance</b> — measures personal growth." },
    { q: "Does formative assessment accelerate or measure learning?", a: "Formative assessment <b>ACCELERATES learning</b> by providing continuous feedback. Summative MEASURES final outcomes." },
    { q: "Is Term End Examination formative or summative?", a: "<b>Summative</b> — NOT formative. It certifies final learning at the end of instruction." },
    { q: "What are the 3 characteristics of a good test?", a: "<b>Reliability</b> (consistent results), <b>Validity</b> (tests what it claims), <b>Objectivity</b> (free from bias). Subjectivity is NOT a characteristic." },
  ],
  brain: [
    { q: "Which brain part controls balance and movement?", a: "<b>Cerebellum</b> — coordinates balance, movement, and motor skills." },
    { q: "Which brain part is critical for recalling NEW information?", a: "<b>Hippocampus</b> — critical for memory formation and recall. Most common PYQ trap: students confuse this with Amygdala." },
    { q: "Which brain part processes emotions and fear?", a: "<b>Amygdala</b> — processes emotions and fear responses. NOT recall. Amygdala ≠ Hippocampus is the #1 brain trap." },
    { q: "Which brain part acts as a relay centre?", a: "<b>Thalamus</b> — relay centre for sensory signals. Also involved in new verbal information." },
    { q: "Are synaptic connections fixed or dynamic?", a: "<b>Dynamic</b> — they can change (neuroplasticity). Brain is not hardwired — it adapts with learning." },
    { q: "Is the adolescent brain the same as the adult brain?", a: "<b>NO</b> — the adolescent brain is DIFFERENT from the adult brain. A common wrong statement in PYQs." },
    { q: "What is the IQ formula?", a: "IQ = (<b>Mental Age ÷ Chronological Age</b>) × 100" },
    { q: "Which is NOT an attribute of intelligence: Reasoning, Judging, Understanding, Feeling?", a: "<b>Feeling</b> — that belongs to emotion and personality, NOT intelligence. Intelligence involves Reasoning, Judging, Understanding." },
    { q: "What shape does the distribution of IQ scores form?", a: "<b>Normal curve / Bell curve</b> — symmetrical distribution with most scores near the average." },
  ],
  communication: [
    { q: "What are the 7 C's of effective communication?", a: "<b>Clarity, Conciseness, Completeness, Correctness, Courtesy, Consideration, Concreteness</b>. Mnemonic: 4C+3C." },
    { q: "Is Competition one of the 7 C's of communication?", a: "<b>NO</b> — Competition is NOT one of the 7 C's. This is a direct PYQ trap. Neither are: Cleverness, Causation, Cessation, Calmness." },
    { q: "Is oral communication faster or slower than written?", a: "<b>FASTER</b> — 'Oral is slower than written' is a direct wrong option in PYQs. Oral is always faster." },
    { q: "What type of communication is a teacher lecturing to students?", a: "<b>One-way communication</b> — information flows only from teacher to students with no feedback loop." },
    { q: "What is a Semantic barrier in communication?", a: "Using <b>jargon, technical terms</b>, or ambiguous language that the receiver doesn't understand." },
    { q: "What is a Physical barrier to communication?", a: "<b>Noise, poor lighting, fatigue, distance</b> — environmental factors blocking the message." },
    { q: "Sender=? Receiver=? Message=? Channel=?", a: "Sender = <b>Source</b>. Receiver = <b>Audience</b>. Message = <b>Contents</b>. Channel = <b>Medium</b>." },
    { q: "What is the function of mass media?", a: "<b>Socialising people</b>. (Negative effect = promotes disturbances. AIR/TV = important unit of mass media.)" },
    { q: "Are easy sentences and simple language barriers or facilitators of communication?", a: "<b>FACILITATORS</b> — not barriers. Easy language helps the message get through clearly." },
    { q: "Who defined communication as 'meaningful interaction among human beings'?", a: "<b>Meferland</b>. This is his definition — NOT a cause of miscommunication." },
  ],
};

export const SEQ_DATA = [
  { id: 'bloom-cog', cat: 'bloom', title: "Bloom's Cognitive Domain", subtitle: "Lowest to Highest", steps: ["Remember", "Understand", "Apply", "Analyse", "Evaluate", "Create"], explain: "Remember = recall facts. Understand = explain in own words. Apply = use in new situation. Analyse = break down. Evaluate = judge/critique. Create = produce something new.", trap: "Create is the HIGHEST (not Evaluate). Lorin Anderson revised this, NOT Bloom.", mnemonic: "RUAAEC — Really Useful Acronyms Always Explain Concepts" },
  { id: 'piaget', cat: 'theories', title: "Piaget's 4 Stages of Cognitive Development", subtitle: "Fixed, established order", steps: ["Sensorimotor (0–2)", "Preoperational (2–7)", "Concrete Operational (7–11)", "Formal Operational (12+)"], explain: "Sensorimotor = senses. Preoperational = language. Concrete = logical about real objects. Formal = abstract reasoning.", trap: "7–11 = Concrete Operational NOT Formal. 12+ = Formal Operational." },
  { id: 'maslow', cat: 'theories', title: "Maslow's Hierarchy of Needs", subtitle: "Lowest to Highest", steps: ["Physiological", "Safety", "Belongingness", "Esteem", "Self-Actualisation"], explain: "Physiological = basic survival. Safety = security. Belongingness = connection. Esteem = respect. Self-Actualisation = potential.", mnemonic: "Please Stop Being Eaten Slowly" },
  { id: '5e', cat: 'teaching', title: "5-E Instructional Model", subtitle: "Constructivist design", steps: ["Engage", "Explore", "Explain", "Elaborate", "Evaluate"], explain: "Engage = hook curiosity. Explore = investigate. Explain = introduce terms. Elaborate = apply new situations. Evaluate = assess.", mnemonic: "Every Explorer Explains Elaborate Events" },
  { id: 'inclusion', cat: 'theories', title: "Segregation to Inclusion", subtitle: "Historical sequence", steps: ["Segregation", "Opening doors", "Accommodation", "Integration", "Inclusion"], explain: "Evolution from separate schools to institution adapting to all students." },
  { id: 'test-prep', cat: 'assessment', title: "Test Preparation Sequence", subtitle: "From purpose to finalized test", steps: ["Define purpose", "Write learning outcomes", "Write test items", "Tryout items", "Finalise"], explain: "Know WHY you are testing first. Then decide what students should know. Then write questions. Then trial them. Then publish final version.", trap: "Purpose comes FIRST before writing anything." },
  { id: 'evaluation', cat: 'assessment', title: "Evaluation of Students Sequence", subtitle: "Standard 5-step process", steps: ["Identify objectives", "Write behavioral objectives", "Select evaluation tools", "Administer tool", "Score and interpret"], explain: "Know what to assess first. Make it measurable. Choose how to assess. Conduct assessment. Analyze results.", trap: "Identifying objectives comes FIRST." },
  { id: 'teaching-seq', cat: 'teaching', title: "Teaching Sequence", subtitle: "Correct order of a teaching session", steps: ["Know prior knowledge", "Set objectives", "Decide topic", "Decide materials", "Introduce topic"], explain: "Always assess what students already know first. Then set goals. Only then introduce topic.", trap: "Prior knowledge check comes FIRST." },
  { id: 'programmed', cat: 'teaching', title: "Programmed Instruction (Skinner)", subtitle: "Forerunner of e-learning", steps: ["Initial Behavior", "Small Steps", "Active Participation", "Immediate Feedback", "Terminal Behavior"], explain: "Start from where student is. Break into tiny steps. Student must actively respond. Reach the target.", trap: "Initial Behavior comes FIRST." },
  { id: 'pedagogical', cat: 'teaching', title: "Pedagogical Analysis Sequence", subtitle: "Steps of lesson planning", steps: ["Content analysis", "Instructional objectives", "Methodology", "Evaluation"], explain: "First analyse the content. Then set what students should achieve. Then choose methods.", trap: "Content analysis is FIRST." },
  { id: 'self-directed', cat: 'andragogy', title: "Self-Directed Learning Sequence", subtitle: "Adult learning process", steps: ["Evaluate readiness", "Establish objectives", "Participate in education", "Evaluate learning"], explain: "First check if the adult learner is ready. Then set goals. Finally evaluate what was learned.", trap: "Evaluate readiness comes FIRST." },
  { id: 'self-assess', cat: 'andragogy', title: "Self-Assessment Sequence", subtitle: "Reflective self-evaluation", steps: ["Getting started", "Select components and descriptors", "Evaluate competences", "Compare perspectives"], explain: "Start the process. Choose what to assess. Evaluate. Then compare with external perspective." },
  { id: 'discipline', cat: 'teaching', title: "Positive Discipline Sequence", subtitle: "Classroom management", steps: ["Set rules (beginning of year)", "Set objectives (class start)", "Reinforce proper conduct", "Give learners choices"], explain: "Rules at START OF YEAR. Objectives at START OF CLASS. Reinforce throughout.", trap: "Rules = BEGINNING OF YEAR." },
  { id: 'cba', cat: 'assessment', title: "Computer-Based Assessment Sequence", subtitle: "Digital assessment workflow", steps: ["Assessment generation", "Assessment delivery", "Scoring and interpretation", "Storage/retrieval/transmission"], explain: "First create the assessment. Then deliver it to students. Then score. Then store data." },
  { id: 'mass-media', cat: 'communication', title: "Mass Communication History", subtitle: "Chronological order", steps: ["Newspapers", "Radio", "Television", "Internet"], explain: "Newspapers came first. Then Radio. Then Television. Then Internet (digital, interactive).", trap: "Newspapers came FIRST — not radio." },
  { id: 'psychology-def', cat: 'theories', title: "Psychology Definition History", subtitle: "Chronological order", steps: ["Science of Soul", "Science of Mind", "Science of Consciousness", "Science of Behaviour"], explain: "Psychology began as study of soul. Then mind. Then consciousness. Then behaviour." },
  { id: 'affective', cat: 'bloom', title: "Affective Domain", subtitle: "Bloom, Krathwohl & Masia 1964", steps: ["Receiving", "Responding", "Valuing", "Organisation", "Characterization"], explain: "Receiving = passive awareness. Responding = active participation. Valuing = attaching worth.", mnemonic: "RRVOC — Really Responding Validates Our Character" },
  { id: 'psychomotor', cat: 'bloom', title: "Psychomotor Domain (Dave 1970)", subtitle: "Lowest to Highest", steps: ["Imitation", "Manipulation", "Precision", "Articulation", "Naturalization"], explain: "Imitation = copy observed action. Manipulation = perform from instructions. Precision = accurate.", mnemonic: "IMPAN — I Must Practice And Naturalise" },
  { id: 'vygotsky-dir', cat: 'theories', title: "Vygotsky's Direction of Learning", subtitle: "Social first, then internal", steps: ["Interpsychological (Social)", "Intrapsychological (Internal)"], explain: "Learning ALWAYS begins socially — between the child and another person. Then it gets internalised.", trap: "'Intra to Inter' is ALWAYS WRONG." },
];

export const TRAP_DATA = [
  { cat: 'communication', wrong: "Oral communication is SLOWER than written communication", correct: "Oral is FASTER than written — always.", rule: "Oral = always FASTER" },
  { cat: 'communication', wrong: "Competition is one of the 7 C's of effective communication", correct: "Competition is NOT one of the 7 C's.", rule: "Competition ≠ 7 C's" },
  { cat: 'communication', wrong: "Easy sentences and simple language are barriers to communication", correct: "They are FACILITATORS — they help the message get through clearly.", rule: "Simple language = Facilitator" },
  { cat: 'assessment', wrong: "Periodic assessment is summative", correct: "Periodic assessment is BOTH formative AND diagnostic — not summative.", rule: "Periodic = Formative + Diagnostic" },
  { cat: 'assessment', wrong: "Term End Examination is formative assessment", correct: "Term End Exam is SUMMATIVE — it certifies learning at the end of instruction.", rule: "Term End = Summative" },
  { cat: 'assessment', wrong: "Subjectivity is a characteristic of a good test", correct: "A good test requires Reliability, Validity, and Objectivity.", rule: "Good test = RVO, NOT subjectivity" },
  { cat: 'theories', wrong: "Vygotsky's direction is intrapsychological to interpsychological", correct: "Always INTER first (social) then INTRA (internal).", rule: "Vygotsky: ALWAYS Inter → Intra" },
  { cat: 'theories', wrong: "Self-speech in children is egocentric behaviour", correct: "Private speech is a THINKING TOOL — not egocentric behaviour.", rule: "Private speech = thinking tool" },
  { cat: 'theories', wrong: "Piaget's stages can be skipped if the child is advanced", correct: "Stages are in a FIXED established pattern — no stage can be skipped.", rule: "Piaget = fixed order, no skipping" },
  { cat: 'theories', wrong: "7–11 years = Formal Operational stage (Piaget)", correct: "7–11 = CONCRETE Operational. 12+ = Formal Operational.", rule: "7–11 = Concrete; 12+ = Formal" },
  { cat: 'theories', wrong: "Bronfenbrenner's theory is a structural theory of learning", correct: "It is an ECOLOGICAL theory (Ecological Systems Theory).", rule: "Bronfenbrenner = ECOLOGICAL" },
  { cat: 'persons', wrong: "Bloom revised his own taxonomy", correct: "Lorin Anderson (Bloom's student) revised it in 2001 — NOT Bloom himself.", rule: "Revised = Anderson, NOT Bloom" },
  { cat: 'persons', wrong: "Malcolm Knowles coined the term Andragogy", correct: "Alexander Kapp coined 'Andragogy' in 1833. Knowles popularised it.", rule: "Coined = Kapp (1833). Popularised = Knowles" },
  { cat: 'brain', wrong: "Amygdala is critical for recalling new information", correct: "Amygdala = EMOTIONS and fear. Hippocampus = recall of NEW information.", rule: "Hippocampus = Recall" },
  { cat: 'brain', wrong: "Feeling is an attribute of intelligence", correct: "Intelligence involves Reasoning, Judging, Understanding. FEELING belongs to personality.", rule: "Feeling ≠ intelligence attribute" },
  { cat: 'pedagogy', wrong: "Pedagogy refers to the 'prospect of teaching'", correct: "Pedagogy = art + science + craft of teaching.", rule: "Pedagogy ≠ Prospect" },
  { cat: 'pedagogy', wrong: "Andragogy classes do not need hands-on experience", correct: "Adult learners BENEFIT greatly from hands-on experience.", rule: "Adult learning = needs hands-on" },
];

export const MT_UNITS = [
  { id: 'u1', name: 'Teaching & Training', num: 'Unit 1' },
  { id: 'u2', name: 'Communication', num: 'Unit 2' },
  { id: 'u3', name: 'Classroom Management', num: 'Unit 3' },
  { id: 'u4', name: 'Assessment', num: 'Unit 4' },
  { id: 'u5', name: 'Educational Technology', num: 'Unit 5' },
  { id: 'u6', name: 'Educational Psychology', num: 'Unit 6' },
  { id: 'u7', name: 'Andragogy', num: 'Unit 7' },
  { id: 'u8', name: 'Learning & Pedagogy', num: 'Unit 8' },
];

export const MT_QUESTIONS: Record<string, any[]> = {
  u1: [
    { q: "Which model corresponds to Memory Level of teaching?", opts: ["Morrison Teaching Model", "Bigge and Hunt Model", "Herbartian Model", "Tassinari Model"], ans: 2, correct: "Memory Level = <b>Herbartian Model</b>.", rule: "Memory→Herbartian" },
    { q: "What is the order of Bloom's revised cognitive taxonomy?", opts: ["Remember, Apply, Understand, Analyse", "Remember, Understand, Apply, Analyse, Evaluate, Create", "Understand, Remember, Apply, Evaluate", "Remember, Understand, Analyse, Apply"], ans: 1, correct: "<b>RUAAEC</b> sequence.", rule: "RUAAEC" },
    { q: "VARK learning style model was developed by?", opts: ["Bandura", "Piaget", "Neil Fleming", "Kahn"], ans: 2, correct: "<b>Neil Fleming</b> developed VARK in 1987.", rule: "VARK = Fleming" },
    { q: "Greatest influence on teaching effectiveness?", opts: ["Class size", "Teacher's subject knowledge and pedagogy", "Online resources", "Administrative support"], ans: 1, correct: "<b>Subject knowledge and pedagogy</b> are most critical.", rule: "Knowledge + Pedagogy = Key" },
    { q: "Kinesthetic learner learns best through?", opts: ["Reading", "Listening", "Videos", "Hands-on and simulation"], ans: 3, correct: "<b>Kinesthetic</b> = hands-on experience.", rule: "Kinesthetic = Hands-on" },
    { q: "Which level of Bloom's taxonomy does 'Recognise linear equations' belong to?", opts: ["Understand", "Apply", "Remember", "Create"], ans: 2, correct: "<b>Remembering</b> is Level 1 recall.", rule: "Recognise = Remember" },
    { q: "Dave's Psychomotor Domain hierarchical order?", opts: ["Precision, Imitation...", "Imitation, Manipulation, Precision...", "Manipulation, Imitation...", "Imitation, Precision..."], ans: 1, correct: "<b>IMPAN</b> sequence.", rule: "IMPAN" },
    { q: "Which of the following is NOT a learner-centered method?", opts: ["Role Play", "Discussion", "Lecture", "Inquiry"], ans: 2, correct: "<b>Lecture</b> is teacher-centered.", rule: "Lecture = Teacher-centered" },
    { q: "Microteaching is?", opts: ["For communication only", "For behaviour only", "Both communication and behaviour modification", "For large groups"], ans: 2, correct: "<b>Both</b> statement are true (PYQ 2025).", rule: "Microteaching = Dual purpose" },
    { q: "Represent graphically is which Bloom's level?", opts: ["Remember", "Understand", "Apply", "Analyse"], ans: 2, correct: "<b>Applying</b> is Level 3 usage.", rule: "Represent = Apply" },
  ],
  u2: [
    { q: "NOT one of the 7 C's of effective communication?", opts: ["Conciseness", "Completeness", "Competition", "Courtesy"], ans: 2, correct: "<b>Competition</b> is NOT a C.", rule: "Competition ≠ 7 C's" },
    { q: "Oral vs Written communication speed?", opts: ["Slower", "Faster", "Same", "Less reliable"], ans: 1, correct: "Oral is <b>FASTER</b>.", rule: "Oral = Faster" },
    { q: "Which is a semantic barrier?", opts: ["Noise", "Technical jargon", "No equipment", "Lack of confidence"], ans: 1, correct: "<b>Jargon</b> is a semantic (meaning) barrier.", rule: "Jargon = Semantic" },
    { q: "Channel corresponds to?", opts: ["Source", "Audience", "Medium", "Contents"], ans: 2, correct: "Channel = <b>Medium</b>.", rule: "Channel = Medium" },
    { q: "Teacher lecturing is?", opts: ["Two-way", "One-way", "Mass", "Non-verbal"], ans: 1, correct: "One-way communication.", rule: "Lecture = One-way" },
    { q: "Meferland's definition of communication?", opts: ["Exchange of ideas", "Process of meaningful interaction", "Transmission", "Sum of things"], ans: 1, correct: "<b>Meaningful interaction</b>.", rule: "Meferland = Meaningful" },
    { q: "Socialising people is mass media's?", opts: ["Effect", "Barrier", "Function", "Unit"], ans: 2, correct: "It is a <b>function</b>.", rule: "Socialise = Function" },
    { q: "Causes of miscommunication?", opts: ["Too many messages, No sequence, Too fast", "Simple language", "Meaningful interaction", "Feedback"], ans: 0, correct: "Overload and speed cause failure.", rule: "Overload = Failure" },
    { q: "Easy sentences are?", opts: ["Barriers", "Noise", "Facilitators", "Semantic"], ans: 2, correct: "<b>Facilitators</b>.", rule: "Easy = Facilitator" },
    { q: "Physical barrier?", opts: ["Jargon", "No confidence", "Strict rules", "Noise"], ans: 3, correct: "<b>Noise</b> is physical.", rule: "Noise = Physical" },
  ],
  u3: [
    { q: "Approach involving 'planting questions'?", opts: ["Permissive", "Authoritative", "Exploratory", "Behaviorist"], ans: 2, correct: "<b>Exploratory</b> approach.", rule: "Plant questions = Exploratory" },
    { q: "UDL stands for?", opts: ["Unified Design", "Universal Document", "Universal Design for Learning", "Unified Document"], ans: 2, correct: "Universal Design for Learning.", rule: "UDL = Universal" },
    { q: "Most effective disruption reduction strategy?", opts: ["Ignore", "Shout", "Clear expectations", "Let them manage"], ans: 2, correct: "<b>Clear expectations</b> prevent trouble.", rule: "Expectations = Prevention" },
    { q: "Segregation to inclusion sequence?", opts: ["Seg, Int, Acc...", "Seg, Open, Acc, Int, Inc", "Int, Seg...", "Seg, Acc..."], ans: 1, correct: "<b>SOAI-I</b> sequence.", rule: "Seg→Open→Acc→Int→Inc" },
    { q: "Integration vs Inclusion?", opts: ["Same", "Int=institution adapts", "Int=student adapts; Inc=institution adapts", "Inc first"], ans: 2, correct: "<b>Inclusion</b> means the system adapts.", rule: "Inclusion = System adapts" },
    { q: "How should a teacher handle minor disruptive behaviour?", opts: ["Humiliate", "Shout", "Non-verbal cues/Quiet address", "Confront"], ans: 2, correct: "Subtle cues are best.", rule: "Minor = Subtle" },
    { q: "Inclusive classroom description?", opts: ["High performers only", "Rules setup", "Every student feels valued", "Teacher boss"], ans: 2, correct: "Belonging and value for all.", rule: "Inclusion = Valued" },
    { q: "Classroom setting is a?", opts: ["Style", "Habit", "Variable", "Feedback"], ans: 2, correct: "It is an environment <b>variable</b>.", rule: "Setting = Variable" },
    { q: "Scaffolding primarily means?", opts: ["Evaluation", "Rules", "Temporary support", "Infrastructure"], ans: 2, correct: "<b>Temporary support</b>.", rule: "Scaffold = Temporary" },
    { q: "Positive discipline sequence?", opts: ["Obj, Rules...", "Rules (year start), Obj (class start), Reinforce...", "Choices first", "Reinforce first"], ans: 1, correct: "Yearly rules then daily objectives.", rule: "Yearly Rules → Daily Objectives" },
  ],
  u4: [
    { q: "Periodic assessments are?", opts: ["Summative", "Formative", "Diagnostic", "Both formative and diagnostic"], ans: 3, correct: "Dual purpose (PYQ 2025).", rule: "Periodic = Formative + Diagnostic" },
    { q: "Which is NOT a good test characteristic?", opts: ["Reliability", "Validity", "Subjectivity", "Objectivity"], ans: 2, correct: "<b>Subjectivity</b> is bias.", rule: "Good test = RVO" },
    { q: "Evaluation sequence?", opts: ["Select, ID...", "Identify obj, Write, Select, Admin, Score", "Admin, Score...", "Write, Admin..."], ans: 1, correct: "Identify objectives first.", rule: "ID Objectives FIRST" },
    { q: "SJT stands for?", opts: ["Standard", "Situational Judgement Test", "Structured", "Systematic"], ans: 1, correct: "Situational Judgement Test.", rule: "SJT = Situational" },
    { q: "Assessment for learning is?", opts: ["Behaviourist", "Constructivist", "Cognitivist", "Humanistic"], ans: 1, correct: "Constructivist perspective.", rule: "AFL = Constructivism" },
    { q: "NOT formative?", opts: ["Observations", "Records", "Term End Exam", "Portfolio"], ans: 2, correct: "Term End is summative.", rule: "Term End = Summative" },
    { q: "CBCS stands for?", opts: ["Content", "Credit", "Choice Based Credit System", "Choice Based Content"], ans: 2, correct: "Choice Based Credit System.", rule: "CBCS = Choice" },
    { q: "Assessment vs own earlier performance?", opts: ["Norm", "Criterion", "Ipsative", "Scholastic"], ans: 2, correct: "<b>Ipsative</b> measures growth.", rule: "Ipsative = Self-growth" },
    { q: "Key component for On-Demand Exam?", opts: ["Study mat", "Question bank", "Books", "Enrolment"], ans: 1, correct: "<b>Question bank</b> is essential.", rule: "On-demand = Question Bank" },
    { q: "Formative assessment primarily does what?", opts: ["Certifies", "Grades", "Accelerates learning", "Measures final"], ans: 2, correct: "It <b>accelerates</b> learning process.", rule: "Formative = Accelerate" },
  ],
  u5: [
    { q: "Which is NOT a video-conferencing tool?", opts: ["Meet", "Zoom", "Moodle", "Webex"], ans: 2, correct: "Moodle is an LMS.", rule: "Moodle = LMS" },
    { q: "Screen recording and editing for digital teaching is done by?", opts: ["Edmodo", "FlipGrid", "Camtasia", "Stormboard"], ans: 2, correct: "Camtasia (PYQ 2025).", rule: "Camtasia = Screen record" },
    { q: "Cloud computing?", opts: ["Weather", "On-demand internet services", "AI", "Installed software"], ans: 1, correct: "Specialized data center services.", rule: "Cloud = On-demand internet" },
    { q: "SWAYAM 4 quadrants include?", opts: ["DBMS", "E-content, E-assessment, Discussion, Web resources", "Conferencing", "AR"], ans: 1, correct: "No DBMS in quadrants.", rule: "SWAYAM = 4Q (No DBMS)" },
    { q: "NOT priority ICT use?", opts: ["Progress", "Attendance", "Exercises", "Presentations"], ans: 1, correct: "Attendance is administrative.", rule: "Attendance = Admin" },
    { q: "AR in education?", opts: ["Virtual env", "Overlay on real world", "Replacement", "Avatars"], ans: 1, correct: "Overlay on real context.", rule: "AR = Overlay" },
    { q: "Adaptive Learning Tech?", opts: ["Fixed", "Adjusts to individual needs", "Traditional", "AI only"], ans: 1, correct: "Automatically adjusts content.", rule: "Adaptive = Adjusts" },
    { q: "E-learning supports which of the following?", opts: ["Individual", "Collaborative", "Both", "Formal"], ans: 2, correct: "Both modes are supported.", rule: "E-learning = Individual + Collab" },
    { q: "Correct ICT data skill?", opts: ["Gather, Store, Email", "Gather, Store, Analyse", "Email, Webinar", "Analyse, Conferencing"], ans: 1, correct: "Gather, store, and analyse.", rule: "Data = GSA" },
    { q: "Principle highlights that technology should be supplementary?", opts: ["Cost", "Authenticity", "Appropriateness", "Organisation"], ans: 2, correct: "Appropriateness (Mayer).", rule: "Tech = Supplementary" },
  ],
  u6: [
    { q: "Which brain structure is critical for recalling new information?", opts: ["Cerebellum", "Amygdala", "Hippocampus", "Thalamus"], ans: 2, correct: "Hippocampus = memory recall.", rule: "Hippocampus = Recall" },
    { q: "Bronfenbrenner's theory is?", opts: ["Structural", "Ecological", "Behaviourist", "Cognitive"], ans: 1, correct: "Ecological Systems Theory.", rule: "Bronfenbrenner = Ecological" },
    { q: "Growing up before mobiles is an example of which system?", opts: ["Micro", "Meso", "Exo", "Chronosystem"], ans: 3, correct: "Chronosystem (Time dimension).", rule: "Era = Chronosystem" },
    { q: "What is the IQ formula?", opts: ["MA*CA", "CA/MA", "MA/CA * 100", "MA+CA"], ans: 2, correct: "MA/CA * 100.", rule: "IQ = MA/CA" },
    { q: "NOT intelligence attribute?", opts: ["Reasoning", "Judging", "Understanding", "Feeling"], ans: 3, correct: "Feeling belongs to emotion.", rule: "Intelligence = RJU" },
    { q: "Vygotsky's learning direction is?", opts: ["Intra to Inter", "Indiv to Social", "Inter to Intra", "Social to Bio"], ans: 2, correct: "Always Inter first.", rule: "Inter FIRST" },
    { q: "Schema theory is primarily associated with?", opts: ["Vygotsky", "Bartlett and Piaget", "Skinner", "Maslow"], ans: 1, correct: "Bartlett and Piaget (PYQ 2025).", rule: "Schema = B + P" },
    { q: "Who developed the Inkblot Test?", opts: ["Cattell", "Morgan", "Rorschach", "Eysenck"], ans: 2, correct: "Hermann Rorschach.", rule: "Inkblot = Rorschach" },
    { q: "Piaget's child moves from one stage to the next in a/an?", opts: ["Random", "Spiral", "Non-linear", "Established pattern"], ans: 3, correct: "Fixed established pattern.", rule: "Piaget = Fixed" },
    { q: "Zone of Proximal Development proposed by?", opts: ["Piaget", "Bronfenbrenner", "Vygotsky", "Bloom"], ans: 2, correct: "Vygotsky.", rule: "ZPD = Vygotsky" },
  ],
  u7: [
    { q: "The term 'Andragogy' was first coined by?", opts: ["Knowles", "Lieb", "Alexander Kapp", "Liegans"], ans: 2, correct: "Alexander Kapp (1833).", rule: "Coined = Kapp" },
    { q: "Andragogy is?", opts: ["Subject-centered", "Teacher-centered", "Learner-centered", "Standardised"], ans: 2, correct: "Learner-centered adult learning.", rule: "Andragogy = Learner-centered" },
    { q: "Which is NOT one of Knowles' hypotheses about Andragogy?", opts: ["Problem-solving", "Immediate importance", "Judgmental", "Understand why"], ans: 2, correct: "Judgmental is never a Knowles hypothesis.", rule: "Judgmental ≠ Knowles" },
    { q: "Which is NOT a characteristic of adult learners?", opts: ["They take ownership", "They are highly teacher-dependent", "Keen to apply to real issues", "Usually internally motivated"], ans: 1, correct: "Adults are self-directed.", rule: "Adults = Self-directed" },
    { q: "Stephen Lieb is associated with?", opts: ["Introducing the term", "Responsibilities", "Motivation and Reinforcement", "Guidelines"], ans: 2, correct: "Motivation and reinforcement.", rule: "Lieb = Motivation" },
    { q: "Adult learners prefer which type of learning?", opts: ["Theoretical", "Teacher-directed", "Practical and Experiential", "Passive"], ans: 2, correct: "Practical application.", rule: "Adults = Practical" },
    { q: "In adult education, pace and timing is influenced by?", opts: ["Curriculum", "Teacher", "Adult learners' availability", "Standards"], ans: 2, correct: "Flexible based on learner availability.", rule: "Pace = Learner-led" },
    { q: "Which is NOT a characteristic of an effective adult trainer (Legans)?", opts: ["Respect", "Actively Engaging", "Force or fear", "Practical application"], ans: 2, correct: "Never teach by fear.", rule: "Force/Fear = Wrong" },
    { q: "In andragogy, learning topics are organised around?", opts: ["Subject matter units", "Life and work situations", "National curriculum", "Academic semesters"], ans: 1, correct: "Real-world context.", rule: "Andragogy = Life/Work" },
    { q: "Which is NOT a characteristic of Andragogy?", opts: ["Collaboration", "Reflective practice", "Self-directed", "Standardised Assessment"], ans: 3, correct: "Favours flexible assessment.", rule: "Standardised ≠ Andragogy" },
  ],
  u8: [
    { q: "The word 'Pedagogy' literally means?", opts: ["To educate", "To lead the child", "To mentor", "To recognise"], ans: 1, correct: "Paidagogos = To lead.", rule: "Pedagogy = Lead" },
    { q: "Which of the following is NOT what pedagogy refers to?", opts: ["Art", "Science", "Prospect of teaching", "Craft"], ans: 2, correct: "Prospect is always the wrong option.", rule: "Pedagogy ≠ Prospect" },
    { q: "Thinkers associated with Critical Pedagogy?", opts: ["Paulo Freire and Henry Giroux", "Loughran and Kapp", "Bloom and Vygotsky", "Freire and Loughran"], ans: 0, correct: "Paulo Freire and Henry Giroux.", rule: "Critical = Freire + Giroux" },
    { q: "The correct sequence of Pedagogical Analysis is?", opts: ["Method first", "Objectives first", "Content first", "Evaluation first"], ans: 2, correct: "Content Analysis is FIRST.", rule: "Content → Obj → Method" },
    { q: "Which is NOT correct about learning objectives?", opts: ["Specific", "Simple to complex", "Covered by the syllabus", "Attainable"], ans: 2, correct: "Syllabus aligns to objectives.", rule: "Objectives drive syllabus" },
    { q: "Organic relation in pedagogy is between?", opts: ["Preparation and Presentation", "Assessment and Evaluation", "Thoughts and Action", "Curriculum and Teaching"], ans: 2, correct: "Thoughts and Action.", rule: "Pedagogy = Thoughts+Action" },
    { q: "Teaching method that generates largest number of ideas?", opts: ["Lecture", "Blended learning", "Brainstorming", "Case study"], ans: 2, correct: "Brainstorming.", rule: "Brainstorming = Volume" },
    { q: "The 5-E instructional model in correct order?", opts: ["Explore first", "Engage, Explore, Explain, Elaborate, Evaluate", "Explain first", "Evaluate first"], ans: 1, correct: "Engage → Explore → Explain.", rule: "5-E = Engage first" },
    { q: "Learner-centred approach in teaching?", opts: ["Lecture", "Demonstration", "Constructivist approach", "Rote learning"], ans: 2, correct: "Constructivist pedagogy.", rule: "Learner-centered = Constructivist" },
    { q: "Course Learning Objectives (CLO) express?", opts: ["Graduate outcomes", "Program outcomes", "Detailed objectives of individual subjects", "Standards"], ans: 2, correct: "Course Learning Objectives.", rule: "CLO = Subject level" },
  ],
};
